CREATE TABLE IF NOT EXISTS users (
	id VARCHAR(36) PRIMARY KEY DEFAULT(UUID()),
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS entries (
	id VARCHAR(36) PRIMARY KEY DEFAULT(UUID()),
	user_id VARCHAR(36) NOT NULL,
	mood VARCHAR(50) NOT NULL,
	notes TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);